### ISSUE TITLE
Practica 2 - Modelo en WebAssembly

### ISSUE THREAD

**Issue by Heidi-19** [SistemasTecTlaxiaco/actividad-8-modelo-en-webassembly-equipopromastergamer777#1]
Subir la practica de modelo en WebAssembly

**Comment by JoseABCruz** [comment]
[Práctica 2 Diseño (José Antonio Balbuena Cruz).pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-modelo-en-webassembly-equipopromastergamer777/files/11539303/Practica.2.Diseno.Jose.Antonio.Balbuena.Cruz.pdf)

**Comment by FedericoVictorianoSierra** [comment]
[Práctica 2 Diseño (Smart Contract) (Federico Victoriano Sierra).pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-modelo-en-webassembly-equipopromastergamer777/files/11539315/Practica.2.Diseno.Smart.Contract.Federico.Victoriano.Sierra.pdf)

**Comment by Heidi-19** [comment]
[Práctica 2 Diseño (Smart Contract).pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-modelo-en-webassembly-equipopromastergamer777/files/11539491/Practica.2.Diseno.Smart.Contract.pdf)

**Comment by SANDRAVELASCO** [comment]
[Práctica 2 Diseño Smart Contract (Sandra Gabriela Velasco Guzmán).pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-modelo-en-webassembly-equipopromastergamer777/files/11539763/Practica.2.Diseno.Smart.Contract.Sandra.Gabriela.Velasco.Guzman.pdf)

**Comment by EdwinOrtiz1412** [comment]
Calificacion: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
